packages:
    # Packages
    - 'shared/*'
    # API
    - 'api'
    - 'ogserve' # Will be replaced by "charts"
    # Webapps
    - 'surveyform'
    - 'surveyadmin'
    - 'results'
    - 'charts' # WIP will replace both results and ogserve
    - 'jobs'
    - 'homepage'
    - 'graphiql'
