packages:
    # Packages
    - 'shared/*'
    # API
    - 'api'
    - 'api2'
    - 'api-internal'
    # Webapps
    - 'surveyform'
    - 'surveyadmin'
    # Tmp remove Gatsby so it uses its own @apollo/client
    # until we figure https://github.com/apollographql/apollo-client
    # The patch used for Next breaks Gatsby... and no patch breaks Next
    - 'results'
    - 'jobs'
    - 'homepage'
    - 'graphiql'
