packages:
    # Packages
    - 'shared/*'
    # CLI tools
    - 'capture'
    # API
    - 'api'
    # Webapps
    - 'surveyform'
    - 'surveyadmin'
    - 'results'
    - 'results-astro'
    - 'charts' # WIP will replace results
    - 'jobs'
    - 'homepage'
    - 'graphiql'
