surveyType: state_of_css

# used for scatterplot chart
totalCountRounded: 9000

currentYear: 2021

allFeatures:
    # layout:
    - grid
    - subgrid
    - flexbox
    - multi_column
    - writing_modes
    - position_sticky
    - logical_properties
    - aspect_ratio
    - content_visibility
    - flexbox_gap
    - break_rules
    - at_container
    # shapes_graphics:
    - shapes
    - object_fit
    - clip_path
    - masks
    - blend_modes
    - filter_effects
    - backdrop_filter
    - color_gamut
    - perspective
    - intrinsic_sizing
    - conic_gradient
    - color_function
    - accent_color
    # interactions:
    - scroll_snap
    - overscroll_behavior
    - overflow_anchor
    - touch_action
    - pointer_events
    - scroll_timeline
    # typography:
    - font_variant
    - initial_letter
    - font_variant_numeric
    - font_display
    - line_clamp
    - variable_fonts
    # accessibility:
    - prefers_reduced_motion
    - prefers_color_scheme
    - prefers_reduced_data
    - color_contrast
    - color_scheme
    - tabindex
    - aria_attributes
    # other_features:
    - variables
    - feature_support_queries
    - containment
    - will_change
    - calc
    - houdini
    - comparison_functions
    - at_property
    - marker

featuresCategories:
    layout:
        - grid
        - subgrid
        - flexbox
        - multi_column
        - writing_modes
        - position_sticky
        - logical_properties
        - aspect_ratio
        - content_visibility
        - flexbox_gap
        - break_rules
        - at_container
    shapes_graphics:
        - shapes
        - object_fit
        - clip_path
        - masks
        - blend_modes
        - filter_effects
        - backdrop_filter
        - color_gamut
        - perspective
        - intrinsic_sizing
        - conic_gradient
        - color_function
        - accent_color
    interactions:
        - scroll_snap
        - overscroll_behavior
        - overflow_anchor
        - touch_action
        - pointer_events
        - scroll_timeline
    typography:
        - font_variant
        - initial_letter
        - font_variant_numeric
        - font_display
        - line_clamp
        - variable_fonts
    accessibility:
        - prefers_reduced_motion
        - prefers_color_scheme
        - prefers_reduced_data
        - color_contrast
        - color_scheme
        - tabindex
        - aria_attributes
    other_features:
        - variables
        - feature_support_queries
        - containment
        - will_change
        - calc
        - houdini
        - comparison_functions
        - at_property
        - marker

allTools:
    # pre_post_processors
    - sass
    - less
    - post_css
    - stylus
    - assembler_css

    # css_frameworks
    - bootstrap
    - materialize_css
    - ant_design
    - semantic_ui
    - bulma
    - foundation
    - ui_kit
    - tachyons
    - primer
    - tailwind_css
    - pure_css
    - halfmoon

    # css_in_js
    - styled_components
    - jss
    - styled_jsx
    - emotion
    - css_modules
    - styled_system
    - stitches
    - fela
    - linaria
    - astroturf
    - twin
    - theme_ui
    - vanilla_extract
    - windi_css

toolsCategories:
    pre_post_processors:
        - sass
        - less
        - post_css
        - stylus
        - assembler_css
    css_frameworks:
        - bootstrap
        - materialize_css
        - ant_design
        - semantic_ui
        - bulma
        - foundation
        - ui_kit
        - tachyons
        - primer
        - tailwind_css
        - pure_css
        - halfmoon
    css_in_js:
        - styled_components
        - jss
        - styled_jsx
        - emotion
        - css_modules
        - styled_system
        - stitches
        - fela
        - linaria
        - astroturf
        - twin
        - theme_ui
        - vanilla_extract
        - windi_css
