surveyId: js2017
startedAt: December 1, 2017
endedAt: December 31, 2017
resultsUrl: https://2017.stateofjs.com/
year: 2017
status: 3 # preview/open/closed
imageUrl: https://static.devographics.com/stateofjs/2016/images/stateofjs2018.png
colors:
  background: #212424;
  primary: #41c7c7
  secondary: #FE6A6A
  text: #e1e1e1