surveyId: css2020 # used as first part of field names
createdAt: October 1, 2020
shareUrl: https://stateofcss.com
questionsUrl: https://survey.stateofjs.com/state-of-css/2020
resultsUrl: https://2020.stateofcss.com/
year: 2020
status: 3 # closed
imageUrl: https://static.devographics.com/stateofcss/2020/images/stateofcss2020.png