query surveyApi {
    survey(survey: state_of_css) {
        browsers: environments(id: browsers, filters: {}, options: {}) {
            id
            year(year: 2021) {
                year
                completion {
                    total
                    count
                    percentage_survey
                }
                facets {
                    id
                    type
                    completion {
                        total
                        percentage_question
                        percentage_survey
                        count
                    }
                    buckets {
                        id
                        count
                        percentage_question
                        percentage_survey
                        entity {
                            homepage {
                                url
                            }
                            name
                            github {
                                url
                            }
                        }
                    }
                }
            }
        }
    }
}
