[context.production]
  environment = { DATA_API_URL = "https://api.devographics.com/graphql", INTERNAL_API_URL = "https://api-internal.devographics.com/graphql" }

[[redirects]]
  from = "/"
  to = "/en-US"
  force = true