export default function Head() {
  return (
    <>
      <title>Devographics Surveys</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width"
      />
      {/* Favicon created using https://realfavicongenerator.net/ */}
      <link rel="icon" href="/favicon.ico" />
      <link rel="manifest" href="/site.webmanifest"></link>
      <link
        rel="mask-icon"
        href="/safari-pinned-tab.svg"
        color="#5bbad5"
      ></link>
      <meta name="msapplication-TileColor" content="#da532c"></meta>
      <meta name="theme-color" content="#ffffff"></meta>
    </>
  );
}
