name: Hourly cron job
on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      # TODO: replace URL with the running survey URL
      - name: 10mn cron job
        run: |
          curl --request POST \
          --url 'https://vulcan-next.vercel.app/api/crons/cron' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
