surveyId: js2019
createdAt: December 1, 2019
shareUrl: https://stateofjs.com
resultsUrl: https://2019.stateofjs.com/
year: 2019
status: 3 # closed
imageUrl: http://static.devographics.com/stateofjs/2019/images/stateofjs2019.png