- twitterName: shadeed9
  fullName: Ahmad Shadeed
  avatarUrl: shadeed9.jpg
  url: https://www.bram.us/2020/11/05/container-queries-are-coming-to-chromium/
  pickName: Container Queries

- twitterName: argyleink
  fullName: Adam Argyle
  avatarUrl: argyleink.jpg
  url: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts
  pickName: Logical Properties

- twitterName: sachagreif
  fullName: Sacha Greif
  avatarUrl: sachagreif.jpg
  url: https://wattenberger.com/blog/css-cascade
  pickName: The CSS Cascade

- twitterName: kilianvalkhof
  fullName: Kilian Valkhof
  avatarUrl: kilianvalkhof.jpg
  url: https://web.dev/content-visibility/
  pickName: Content-Visibility

- twitterName: christianoliff
  fullName: Christian Oliff
  avatarUrl: christianoliff.jpg
  url: https://purgecss.com/
  pickName: PurgeCSS

- twitterName: walterstephanie
  fullName: Stéphanie Walter
  avatarUrl: walterstephanie.jpg
  url: https://www.youtube.com/c/LayoutLand
  pickName: Jen Simmons' Layout Land

- twitterName: piccalilli_
  fullName: Andy Bell
  avatarUrl: piccalilli_.jpg
  url: https://css-irl.info/
  pickName: CSS IRL

- twitterName: sarasoueidan
  fullName: Sara Soueidan
  avatarUrl: sarasoueidan.jpg
  url: https://rachelandrew.co.uk/
  pickName: Rachel Andrew

- twitterName: 5t3ph
  fullName: Stephanie Eckles
  avatarUrl: 5t3ph.jpg
  url: https://www.youtube.com/watch?v=o6ssu5oKyaU
  pickName: Writing even more CSS with Accessibility in Mind

- twitterName: hugogiraudel
  fullName: Hugo “Kitty” Giraudel
  avatarUrl: hugogiraudel.jpg
  url: https://fela.js.org/
  pickName: Fela

- twitterName: foolip
  fullName: Philip Jägenstedt
  avatarUrl: foolip.jpg
  url: https://blogs.igalia.com/svillar/2020/10/01/closing-the-gap-in-flexbox/
  pickName: Sergio Villar

- twitterName: jina
  fullName: Jina Anne
  avatarUrl: jina.jpg
  url: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
  pickName: prefers-reduced-motion
