# From root directory, you can run "just surveyform/<your-command>"
analyze-bundle-storybook: 
    ANALYZE=true pnpm run build:storybook

analyze-bundle: 
    ANALYZE=true pnpm run build

auto-changelog: 
    pnpm exec auto-changelog -u