/**
 * Temporary user data with unhashed email
 *
 * Must never be stored in the database, we must replace the email by a emailHash
 */
export type NewUserDocument = Omit<UserDocument, "emailHash" | "groups"> & {
  email?: string;
  // groups can be autogenerated on user creation and are optional
  groups?: UserDocument["groups"];
};

export type UserDocument = {
  _id?: string;
  /** @deprecated There is no admin on surveyform anymore */
  isAdmin?: boolean;
  /** 
   * For passwordless, false until the user clicked the magic link for the first time 
   * TODO: verify spec for anon user: they should probably stay always unverified
   **/
  isVerified?: boolean;
  groups: Array<string>;
  /**
   * TODO: is it still used?
   */
  meta?: {
    surveyId,
    editionId,
  }
} & (
    | {
      /**
       * Legacy password based auth
       */
      authMode: undefined | "password";
      emailHash: string;
      emailHash2: string
    }
    | { authMode: "anonymous"; emailHash?: undefined, emailHash2?: undefined }
    | {
      authMode: "passwordless";
      emailHash: string;
      emailHash2: string
    }
  );

/**
 * Minimal structure to authenticate via email
 */
export type EmailUser = { _id?: string, emailHash?: string, emailHash2?: string }